### ISSUE TITLE
A question about tensorboardx used in code

### ISSUE THREAD

**Issue by Jimmy880** [andy840314/QANet-pytorch-#4]
After running your code in GPU, i wanted to visualize the result in tensorboard. I run "tensorboard ./log/" in the directory, but i got the error:  `ValueError: A logdir must be specified when db is not specified. Run "tensorboard --help" for details and examples.` However, after i run commend: `tensorboard --logdir ./log/.` i got the website successfully. 
So i wander weather you wrote the wrong commend or i misunderstand it.

**Comment by andy840314** [comment]
You are right, I wrote my command wrong. I will fix my readme. Thanks!
